# Generated by Django 3.1.1 on 2020-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoitems', '0003_historicaltodoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltodoitem',
            name='expected_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='expected_finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
